#!/usr/bin/env ruby

require "markdown_formatter"
require "optparse"

options = {}

opt_parse = OptionParser.new do |opt|
  opt.banner = 'Usage: mdfmt [options] markdownfile'
  opt.on('-w', '--overwrite', 'overwrite file instead of stdout') { options[:overwrite] = true }
  opt.on('-v', '--version', 'display the version.') { options[:version] = true }
  opt.parse!(ARGV)
end

filepath = ARGV.first

MarkdownFormatter::OPTIONS.merge!(options)

case
  when options[:version]
    puts "MarkdownFormatter version: #{MarkdownFormatter::VERSION}"
  when filepath.nil?
    puts opt_parse
  else
    MarkdownFormatter::CLI.run(filepath.chomp)
end

